# Generated by Django 3.1.6 on 2021-02-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_thought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='thought_text',
            field=models.TextField(),
        ),
    ]
